title:             Alt 254
email:             jbelmonte521@gmail.com
description:       A Blog by Joseph Belmonte
author:            Joseph Belmonte, EIT
baseurl:           "/blog"
url:               "http://jmb93.github.io"

# Social Profiles
twitter_username:  belmonte_j
github_username:   jmb93
facebook_username: n/a
linkedin_usernmae: jmb2393

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
